name: My first Javascript Action

on: [push]
  
   

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: hello-action
        uses: ./.github/actions/hello-world
