name: 'Checkout'
description: 'Checkout a Git repository at a particular 
version'
inputs:[push]
 repository:
 description: 'Repository name with owner. For example, 
actions/checkout'
 default: ${{ github.repository }}
(…)

runs:
 using: node12
 main: dist/index.js
 post: dist/index.js